
#ifndef COMMANDS_H
#define COMMANDS_H

#define CMD_BYTE_CMD_MASK 0xE0
#define CMD_BYTE_FLAG_MASK 0x1F

#define CMD_BYTE_PULSE_CPLD 0x20
#define CMD_BYTE_PULSE_JTAG 0x40

#define CMD_BYTE_PULSE_FLAG_TMS 0x01
#define CMD_BYTE_PULSE_FLAG_TDI 0x02
#define CMD_BYTE_PULSE_FLAG_TDO 0x04
#define CMD_BYTE_PULSE_FLAG_CHK 0x08
#define CMD_BYTE_PULSE_FLAG_SYN 0x10

#define CMD_BYTE_SYNC_CPLD 0x60
#define CMD_BYTE_SYNC_JTAG 0x80

#define CMD_BYTE_REPORT_CPLD 0xa0
#define CMD_BYTE_REPORT_JTAG 0xc0

#define CMD_BYTE_REPORT_FLAG_TDO 0x01
#define CMD_BYTE_REPORT_FLAG_ERR 0x02

#endif /* COMMANDS_H */

